### ISSUE TITLE
how can eml2html be run?

### ISSUE THREAD

**Issue by baloe** [barthez/eml2html#1]
hey barthez,
I just started working on a eml2html converter myself, but I would use yours instead for there's no reason to reinvent the wheel. I'm not familiar with ruby, and I don't get the program to run.

So when I run
`../eml2html/bin/eml2html test.eml`
in my linux terminal I get:

```
../eml2html/bin/eml2html test.eml /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- eml2html (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from ../eml2html/bin/eml2html:3:in `<main>'
```

Are there any prerequisites I need to be aware of?
Thanks.

**Comment by baloe** [comment]
okay, got it! Installed it via `gem2.0 install eml2html`
However, now it throws the following errors:

```
/var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:97:in `block in replace_images_src': undefined method `name' for nil:NilClass (NoMethodError)
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:95:in `gsub'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:95:in `replace_images_src'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:69:in `html_body'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:30:in `save_html'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:21:in `block in save_files!'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:20:in `each'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/lib/eml2html/converter.rb:20:in `save_files!'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/bin/eml2html:28:in `run!'
    from /var/lib/gems/2.0.0/gems/eml2html-0.0.2/bin/eml2html:33:in `<top (required)>'
    from /usr/local/bin/eml2html:23:in `load'
    from /usr/local/bin/eml2html:23:in `<main>'
```

**Comment by acolchagoff** [comment]
I've run into the same error. It appears to be a bug.

**Comment by acolchagoff** [comment]
This happens when an eml file has a body that has a cid that isn't included in the attachments.
